package com.msp.backend.modules.report;

import com.msp.backend.modules.settlement.Settlement;
import com.msp.backend.modules.transaction.Transaction;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.PrintWriter;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

@Service
public class FileGeneratorService {

    private static final DateTimeFormatter DT_FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    public byte[] generateTransactionsCsv(List<Transaction> transactions) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PrintWriter writer = new PrintWriter(out);

        writer.println("Transaction ID,Merchant,Payment Channel,Amount,Nett Amount,Discount,Currency,Status,Ref No,Card No,Txn Date,Posted Date,Description");

        for (Transaction t : transactions) {
            writer.printf("%d,\"%s\",%s,%.2f,%.2f,%.2f,%s,%s,%s,%s,%s,%s,\"%s\"%n",
                    t.getTransactionId(),
                    escapeCsv(t.getMerchantName()),
                    t.getPaymentChannel() != null ? t.getPaymentChannel() : "",
                    t.getAmount() != null ? t.getAmount() : java.math.BigDecimal.ZERO,
                    t.getNettAmount() != null ? t.getNettAmount() : java.math.BigDecimal.ZERO,
                    t.getDiscountAmount() != null ? t.getDiscountAmount() : java.math.BigDecimal.ZERO,
                    t.getCurrency() != null ? t.getCurrency() : "",
                    t.getStatus() != null ? t.getStatus() : "",
                    t.getRefNo() != null ? t.getRefNo() : "",
                    t.getCardNo() != null ? t.getCardNo() : "",
                    t.getTxnDate() != null ? t.getTxnDate().format(DT_FMT) : "",
                    t.getPostedDate() != null ? t.getPostedDate().format(DT_FMT) : "",
                    escapeCsv(t.getTxnDescription())
            );
        }

        writer.flush();
        return out.toByteArray();
    }

    public byte[] generateSettlementsCsv(List<Settlement> settlements) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PrintWriter writer = new PrintWriter(out);

        writer.println("Settlement ID,Settlement No,Settlement Type,Credit Advice ID,Currency,Settlement Amount,Payment Amount,Settlement Date");

        for (Settlement s : settlements) {
            writer.printf("%d,%s,%s,%s,%s,%.2f,%.2f,%s%n",
                    s.getSettlementId(),
                    s.getSettlementNo() != null ? s.getSettlementNo() : "",
                    s.getSettlementType() != null ? s.getSettlementType() : "",
                    s.getCreditAdviceId() != null ? s.getCreditAdviceId().toString() : "",
                    s.getCurrency() != null ? s.getCurrency() : "",
                    s.getSettlementAmount() != null ? s.getSettlementAmount() : java.math.BigDecimal.ZERO,
                    s.getPaymentAmount() != null ? s.getPaymentAmount() : java.math.BigDecimal.ZERO,
                    s.getSettlementDate() != null ? s.getSettlementDate().format(DT_FMT) : ""
            );
        }

        writer.flush();
        return out.toByteArray();
    }

    public byte[] generateSummaryReportCsv(Map<String, Object> reportData) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PrintWriter writer = new PrintWriter(out);

        writer.println("Metric,Value");
        writer.printf("Report Type,%s%n", reportData.getOrDefault("type", ""));
        writer.printf("Generated By,%s%n", reportData.getOrDefault("generatedBy", ""));
        writer.printf("Generated At,%s%n", reportData.getOrDefault("generatedAt", ""));
        writer.println();

        if ("ADMIN_SUMMARY".equals(reportData.get("type"))) {
            writer.printf("Total Users,%s%n", reportData.getOrDefault("totalUsers", "0"));
            writer.printf("Total Merchants,%s%n", reportData.getOrDefault("totalMerchants", "0"));
            writer.printf("Active Merchants,%s%n", reportData.getOrDefault("activeMerchants", "0"));
            writer.printf("Pending Merchants,%s%n", reportData.getOrDefault("pendingMerchants", "0"));
            writer.printf("Suspended Merchants,%s%n", reportData.getOrDefault("suspendedMerchants", "0"));
        } else {
            writer.printf("Merchant Name,%s%n", reportData.getOrDefault("merchantName", ""));
            writer.printf("Merchant Status,%s%n", reportData.getOrDefault("merchantStatus", ""));
        }

        writer.printf("Total Transactions,%s%n", reportData.getOrDefault("totalTransactions", "0"));
        writer.printf("Approved Transactions,%s%n", reportData.getOrDefault("approvedTransactions", "0"));
        writer.printf("Pending Transactions,%s%n", reportData.getOrDefault("pendingTransactions", "0"));
        writer.printf("Declined Transactions,%s%n", reportData.getOrDefault("declinedTransactions", "0"));
        writer.printf("Total Settlements,%s%n", reportData.getOrDefault("totalSettlements", "0"));

        writer.flush();
        return out.toByteArray();
    }

    private String escapeCsv(String value) {
        if (value == null) return "";
        return value.replace("\"", "\"\"");
    }
}
